### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by NathanielJBrown97**
Koch's Snowflake class files; starter code. Effectively established a graphic window, class with private/public members. Setters, and computational helpers to find center or top points between two given 2d vectors of floats. The program works when implemented in main. 

**Upon approval - the main.cpp file will NOT be updated within Version1.0; simply uploaded for testing this current iteration of kochsnowflake class.

Needs:
- Recursive implementation; building blocks are there with helpers to find center/top locations.
- Flexibility of taking parameters to determine color
- Method to output as an image for the requirements of the project.

### CODE REVIEW

**Review by NathanielJBrown97 — COMMENTED** [review]
Just swapped a file name (main -> koch_main) so others can upload their version of the ui integration if desired.

**Review by asampalis — COMMENTED** [review]
looks good

**Review by mllebexx — APPROVED** [review]
Keep up the good work!

**Comment by mllebexx** [comment]
Reviewed.

**Pull request merged**
